complete ticket-6
megbuna/nc-games pull request #4
Opened 2023-01-11 00:33 UTC by megbuna

2023-01-11 09:17 UTC, lewispricey requested changes
Great work so far Michael, checking the comments length and returning a message if there are no comments is a great way to indicate this to the user!

I'll send over a screenshot in a slack DM but when I tested your app on mobile the styling got very squewed and the text was very difficut to read. I'd recommend using mobile view on your browser and changing the styling with your view like this to fix it.

I haven't gone though the votes section as when I tested this the count was increasing on screen but not when I refreshed (this is the next ticket so not to worry)

Overall really good work, your code is very clear! Please fix the mobile view and resubmit a pull request once thats been done 😄

2023-01-11 09:17 UTC, lewispricey commented on src/components/CommentList.jsx
> +    listOfComments.length === 0 ?  (<div><p> No comments yet </p>
Really like the way you're checking the comments length and displaying a message if they don't exist 👍

2023-01-11 09:17 UTC, lewispricey commented on src/components/CommentList.jsx
> +            listOfComments.map(({body, votes, author, created_at, comment_id, review_id}) => {
Great use of destructuring here to grab just the information you need, keeps the code really clear!

2023-01-11 09:17 UTC, lewispricey commented on src/components/CommentCard.jsx
> +    <div className="commentCard">
Is there a more semantic HTML tag you could use here instead of a div?

2023-01-12 10:14 UTC, leekli approved these changes
Thanks for making the styling changes, this looks better in mobile view - well done!

You are free to merge ticket 6.

2023-01-12 10:22 UTC, merged